# Generated by Django 5.2.13 on 2026-04-30 22:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_study_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pk', models.CompositePrimaryKey('study_id', 'submission_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='api.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
